version: "3.8"

services:
  gateway-service:
    image: florinrm/cloud-computing:gateway
    ports:
      - 3000:80
    environment:
      BOOKS_SERVICE_API_ROUTE: books-service/api
      NODE_ENV: development
    networks:
      - gate
  
  books-service:
    image: florinrm/cloud-computing:books
    environment:
      IO_SERVICE_API_ROUTE: io-service/api
      NODE_ENV: development
    networks:
      - gate
      - books
  
  io-service:
    image: florinrm/cloud-computing:io
    environment:
      PGUSER: admin
      PGPASSWORD: admin
      PGHOST: db
      PGPORT: 5432
      PGDATABASE: books
      NODE_ENV: development
    networks:
      - books
      - database
      
  db:
    image: postgres:12
    environment:
      POSTGRES_DB: books
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - ./Database/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
      - homework-db:/var/lib/postgresql/data
    networks:
      - database
      - db-admin
      
  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - db-admin

volumes:
  homework-db:

networks:
  gate:
  books:
  database:
  db-admin: